### ISSUE TITLE
Zotero not coming up in 6.3 and UI issues (toolbar and icon style)

### ISSUE THREAD

**Issue by bijang** [zotero/zotero-libreoffice-integration#48]
Not seeing zotero toolbar anymore despite reinstallation, is this because java components are removed now? 
Also from a UI side, it was previously disappearing when using anything but the standard toolbar, 
understandably extensions probably havn't been figured into the various tollbar UI options yet, though they would need to be for the future.... 
and finally one last gripe, if things were to need  a change, could the zotero icons fall in line with the the various other popular UI icon choices that may be in use (colibre breeze sifr elementary etc)?

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

> Not seeing zotero toolbar anymore despite reinstallation, is this because java components are removed now?

The toolbar works with 6.3 as it is. See https://www.zotero.org/support/word_processor_plugin_troubleshooting#toolbar_is_missing and post on the forums if you still can't get it to show up.

> Also from a UI side, it was previously disappearing when using anything but the standard toolbar,
understandably extensions probably havn't been figured into the various tollbar UI options yet, though they would need to be for the future....

See https://github.com/zotero/zotero-libreoffice-integration/issues/46 for updates

> and finally one last gripe, if things were to need a change, could the zotero icons fall in line with the the various other popular UI icon choices that may be in use (colibre breeze sifr elementary etc)?

This is unlikely to happen as things stand now due to limited design time we have and the relatively small percentage of Zotero users using it with Linux and LibreOffice.
